config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "/exercise_templates", to: "exercises#templates", as: :exercise_templates
  
  root "programs#quick_start"
  resources :users
  resources :programs do
    get :quick_start
    resources :workouts do
      member do
        get :copy_exercise
        get :start_workout
        get :preview_workout
      end
      resources :exercises do
        member do
          post :duplicate
          get :quick_sets_creation
        end
        resources :exercise_sets do
          member do
            post :duplicate
            get  :set_play_form
            get  :play_set
          end
        end
      end
    end
  end
end

app/models/program.rb
class Program < ApplicationRecord
  belongs_to :user
  has_many :workouts, dependent: :destroy
  belongs_to :unit, optional: true

  # attributes: 
  # name String
  # frequency Integer
  # level String
  # goal String
  # min_time Integer
  # max_time Integer
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, except: [:index, :new, :create, :quick_start]
  before_action :authorize_program, only: [:destroy, :edit, :update]
  before_action :form_options, only: [:new, :create, :edit, :update]

  def show
  end

  def index
    @programs = current_user.programs
  end

  def edit
    render :form
  end

  def update
    if @program.update(program_params)
      redirect_to @program, notice: "Your program was successfully updated."
    else
      render :form
    end
  end

  def destroy
    @program.destroy
    redirect_to programs_path, notice: "Program was successfully deleted."
  end

  def new
    @program = current_user.programs.new
    @program.unit ||= Unit.find_by(name: "Minutes")
    render :form
  end

  def create
    @program = current_user.programs.new(program_params)
    if @program.save
      redirect_to @program, notice: "Your program was successfully created."
    else
      render :form, status: :unprocessable_entity
    end
  end

  def quick_start
    @programs = current_user.programs.order(created_at: :desc)
  end

  private

  def set_program
    @program = Program.find(params[:id])
  end

  def form_options
    @units = Unit.where(unit_type: "Time")
    @levels = ['Beginner', 'Intermediate', 'Advanced', 'All levels']
  end

  def authorize_program
    unless authorize
      redirect_to programs_path(), alert: "Not allowed to modify this program."
    end
  end

  def program_params
    params.require(:program).permit(:name, :frequency, :level, :goal, :duration, :unit_id)
  end
end

app/views/programs/edit.html.haml
.form
  %h1.title Edit Program
  = form_for @program do |f|
    .form-group
      = f.label :name
      = f.text_field :name, class: "form-control"

    .form-group
      = f.label :frequency, "Workouts per Week"
      = f.number_field :frequency, class: "form-control"

    .form-group
      = f.label :level
      = f.select :level, ['Beginner', 'Intermediate', 'Advanced', 'All levels'], {}, class: "form-control"

    .form-group
      = f.label :goal
      = f.text_field :goal, class: "form-control"

    .form-group
      = f.label :duration
      = f.number_field :duration, class: "form-control"

    .form-group
      = f.label :unit_id, "Preferred Unit"
      = f.collection_select :unit_id, Unit.where(unit_type: "Time"), :id, :name, { prompt: "Select Unit" }, class: "form-control"

    = f.submit "Save", class: "btn btn-primary"

app/views/programs/form.html.haml
.form
  = form_for @program do |f|
    .form-group
      = f.label :name
      = f.text_field :name, required: true, class: "form-control"
    .form-group
      = f.label :frequency, "Workouts per Week"
      = f.number_field :frequency, step: 1, required: true, class: "form-control"
    .form-group
      = f.label :level
      = f.select :level, @levels, {}, class: "form-control"
    .form-group
      = f.label :goal
      = f.text_field :goal, class: "form-control"
    .form-group-inline
      .field
        = f.label :duration
        = f.number_field :duration, class: "form-control"
      .field
        = f.label :unit_id
        = f.collection_select :unit_id, @units, :id, :name, { prompt: "Select Unit" }, class: "form-control"
    = f.submit "Save", class: "btn btn-primary"

app/views/programs/index.html.haml
.title
  %h1 My Programs
  = link_to new_program_path(), class: "btn btn-outline-primary btn-sm" do
    %i.bi.bi-plus.h4
.index
  %table
    %thead
      %tr
        %th Name
        %th Frequency
        %th Level
        %th Goal
        %th Duration
        %th Time Unit
        %th Actions
    %tbody
      - @programs.each do |program|
        %tr
          %td= program.name
          %td= program.frequency
          %td= program.level
          %td= program.goal
          %td= program.duration
          %td= program.unit&.abbreviation
          %td.actions
            = link_to program_path(program), class: "btn" do
              %i.bi.bi-eye
            - if current_user.programs.include?(program)
              = link_to edit_program_path(program), class: "btn" do
                %i.bi.bi-pencil
              = button_to program_path(program), method: :delete, data: { confirm: "Are you sure?" }, class: "btn delete link" do
                %i.bi.bi-trash

app/views/programs/quick_start.html.haml
- if @programs.any?
  - @programs.each do |program|
    .show-width
      .flex-row
        %h2= program.name
      - workouts = program.workouts.sort_by{ |w| w.last_performed_at }
      - if workouts.any?
        .carousel.slide{ id: "carousel-#{program.id}", data: { bs_ride: "false", bs_interval: "false" } }
          .carousel-inner
            - workouts.each_with_index do |workout, index|
              .carousel-item{ class: (index == 0 ? "active" : "") }
                .d-flex.justify-content-center.align-items-center{ style: "min-height: 150px;" }
                  = link_to workout.name, start_workout_program_workout_path(program, workout), class: "btn btn-success btn-lg"
          %button.carousel-control-prev{ type: "button", data: { bs_target: "#carousel-#{program.id}", bs_slide: "prev" } }
            %span.carousel-control-prev-icon{ aria: { hidden: "true" } }
            %span.visually-hidden Previous
          %button.carousel-control-next{ type: "button", data: { bs_target: "#carousel-#{program.id}", bs_slide: "next" } }
            %span.carousel-control-next-icon{ aria: { hidden: "true" } }
            %span.visually-hidden Next
    .separator

:scss

  .show-width {
    .flex-row {
      padding-top: 15px;
      padding-bottom: 15px;
    }
  }

  .carousel-control-prev-icon {
    background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='%23000' viewBox='0 0 8 8'%3E%3Cpath d='M5.25 0l-4 4 4 4 1.5-1.5-2.5-2.5 2.5-2.5-1.5-1.5z'/%3E%3C/svg%3E") !important;
  }

  .carousel-control-next-icon {
    background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='%23000' viewBox='0 0 8 8'%3E%3Cpath d='M2.75 0l-1.5 1.5 2.5 2.5-2.5 2.5 1.5 1.5 4-4-4-4z'/%3E%3C/svg%3E") !important;
  }

app/views/programs/show.html.haml
.title
  %h1 Program
  - if current_user.programs.include?(@program) 
    = link_to edit_program_path(@program), class:  "btn btn-outline-primary btn-sm" do
      %i.bi.bi-pencil.h5
    = link_to new_program_workout_path(@program), class: "btn btn-outline-primary btn-sm", title: "Add workout" do
      %i.bi.bi-plus.h5
.show
  %table
    %tbody
      %tr
        %td.label Name:
        %td.value= @program.name
      %tr
        %td.label Frequency:
        %td.value= @program.frequency
      %tr
        %td.label Goal:
        %td.value= @program.goal
      %tr
        %td.label Level:
        %td.value= @program.level
      - if @program.duration
        %tr
          %td.label Estimated Duration:
          %td.value= [@program.duration, @program.unit.abbreviation].join(" ")
  = link_to "Workouts", program_workouts_path(@program), class: "btn btn-primary" if @program.workouts.any?
- if @program.workouts.any?
  .separator
  .show-width
    .flex-row
      - @program.workouts.each do |workout|
        = link_to workout.name, start_workout_program_workout_path(@program, workout), class: "btn btn-success btn-md"
  .separator