config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "/exercise_templates", to: "exercises#templates", as: :exercise_templates
  
  root "programs#quick_start"
  resources :users
  resources :programs do
    get :quick_start
    resources :workouts do
      member do
        get :copy_exercise
        get :start_workout
        get :preview_workout
      end
      resources :exercises do
        member do
          post :duplicate
          get :quick_sets_creation
        end
        resources :exercise_sets do
          member do
            post :duplicate
            get  :set_play_form
            get  :play_set
          end
        end
      end
    end
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_program, except: [:templates]
  before_action :set_workout, except: [:templates]
  before_action :set_exercise, except: [:index, :new, :create, :templates]
  before_action :authorize_exercise, only: [:new, :create, :destroy, :edit, :update]
  before_action :form_options, only: [:new, :create, :edit, :update]

  def index
    @exercises = @workout.exercise_groups.order(:order).includes(:exercises).flat_map(&:exercises)
  end

  def show
  end

  def edit
    render :form
  end

  def update
    warmup_sets = exercise_params[:warmup_sets]&.to_i
    working_sets = exercise_params[:working_sets]&.to_i
    unit = exercise_params[:unit_id]&.to_i
    if warmup_sets && working_sets && unit
      current_set = 1
      warmup_sets.times do
        ds = @exercise.exercise_sets.new(order: current_set, set_type: "Warmup Set", reps: 5, unit_id: unit, suggested_intensity: 5)
        ds.save!
        current_set += 1
      end
      working_sets.times do
        ds = @exercise.exercise_sets.new(order: current_set, set_type: "Working Set", reps: @exercise.rep_range_min, unit_id: unit, suggested_intensity: 8)
        ds.save!
        current_set += 1
      end
      redirect_to program_workout_exercise_exercise_sets_path(@program, @workout, @exercise), notice: "Exercise sets created successfully."
    elsif @exercise.update(exercise_params)
      respond_to do |format|
        format.html { redirect_to program_workout_exercises_path(@program, @workout), notice: "Exercise updated successfully." }
        format.json { render json: { notes: @exercise.notes, id: @exercise.id } }
      end
    else
      respond_to do |format|
        format.html { render :form, status: :unprocessable_entity }
        format.json { render json: { errors: @exercise.errors.full_messages }, status: :unprocessable_entity }
      end
    end
  end

  def new
    order = (@workout&.exercise_groups.select{ |eg| eg.exercises.any? }.map(&:order).max || 0) + 1
    @exercise_group = @workout.exercise_groups.find_by(order: order)
    unless @exercise_group
      @exercise_group = @workout.exercise_groups.new(order: order)
      @exercise_group.save!
    end
    @exercise = @exercise_group.exercises.new
    render :form
  end

  def create
    @exercise_group = @workout.exercise_groups.find(exercise_params[:exercise_group_id])
    @exercise = @exercise_group.exercises.new(exercise_params)
    if @exercise.save
      redirect_to program_workout_exercises_path(@program, @workout), notice: "Your exercise was successfully created."
    else
      render :form, status: :unprocessable_entity
    end
  end

  def destroy
    exercise_group = @exercise.exercise_group
    if exercise_group.exercises.one?
      higher_order_groups = @workout.exercise_groups.where("exercise_groups.order > ?", exercise_group.order)
      higher_order_groups.each do |eg|
        eg.update(order: eg.order - 1)
      end
      exercise_group.destroy
    end
    @exercise.destroy
    redirect_to program_workout_exercises_path(@program, @workout), notice: "Exercise deleted successfully."
  end

  def templates
    template_exercises = Exercise.where(template: true).includes(:instrument, :unit, :muscles)
    @muscle_group = MuscleGroup.find(params[:muscle_group]) if params[:muscle_group]
    @muscle_group ||= MuscleGroup.find_by(name: "Back")
    @muscle = Muscle.find(params[:muscle]) if params[:muscle]
    @template_exercises = template_exercises.where(primary_muscle_group_id: @muscle_group)
    if @muscle
      @template_exercises = @template_exercises.select{ |e| e.muscles.include?(@muscle) }
    end
    @select_options = MuscleGroup.where(template: true).order(created_at: :asc)
    @workout = @template_exercises.first&.exercise_group&.workout
    @program = @workout&.program
  end

  def duplicate
    original = Exercise.find(params[:id])
    copy = original.dup
    copy.save!
    redirect_to edit_program_workout_exercise_path(@program, @workout, copy), notice: "Exercise duplicated."
  end

  def quick_sets_creation
  end

  private

  def set_program
    @program = Program.find(params[:program_id])
  end

  def set_workout
    @workout = @program.workouts.find(params[:workout_id])
  end

  def set_exercise
    @exercise = @workout.exercises.find(params[:id])
  end

  def form_options
    @exercise_groups = @workout.exercise_groups.order(:order)
    @exercise_types = ["Compound", "Isolation"]
    @boolean = [["No", false], ["Yes", true]]
    @instruments =  Instrument.all
    @attachments = Attachment.all
    @grips = Grip.all
    @units = Unit.where(unit_type: "Time")
  end

  def authorize_exercise
    unless authorize
      redirect_to program_workout_exercises_path(@program, @workout), alert: "Not allowed to modify this exercise."
    end
  end

  def exercise_params
    params.require(:exercise).permit(:name, :image, :notes, :exercise_type, :rep_range_min, :rep_range_max, :rest_time, :unilateral, :exercise_group_id,
      :body_weight, :instrument_id, :attachment_id, :hole, :grip_id, :unit_id, :warmup_sets, :working_sets)
  end
end

app/views/exercises/form.html.haml
.form
  = form_with model: [@program, @workout, @exercise], local: true do |f|
    .form-group
      = f.label :name
      = f.text_field :name, required: true
    .form-group
      = f.label :exercise_group_id, "Workout Priority"
      = f.collection_select :exercise_group_id, @exercise_groups, :id, :order, prompt: "Select Order Priority"
    .form-group
      = f.label :exercise_type
      = f.select :exercise_type, @exercise_types
    .form-group
      = f.label :body_weight, "Include Body Weight"
      = f.select :body_weight, @boolean
    .form-group
      = f.label :instrument_id
      = f.collection_select :instrument_id, @instruments, :id, :name
    - if @exercise&.instrument&.name == "Cable"
      .form-group
        = f.label :attachment_id
        = f.collection_select :attachment_id, @attachments, :id, :name, prompt: "Select Cable Attachment"
      .form-group
        = f.label :hole, "Cable Position From Top"
        = f.number_field :hole, placeholder: "Position on Cable (optional)", step: 1
    .form-group
      = f.label :grip_id
      = f.collection_select :grip_id, @grips, :id, :name, prompt: "Select Grip (optional)"
    .form-group-inline
      = f.label :rep_range
    .form-group-inline
      .field
        = f.number_field :rep_range_min, placeholder: "Min", required: true
      .field
        = f.number_field :rep_range_max, placeholder: "Max", required: true
    .form-group-inline
      = f.label :rest_time
    .form-group-inline
      .field
        = f.number_field :rest_time, required: true
      .field
        = f.collection_select :unit_id, @units, :id, :name
    .form-group
      = f.label :unilateral
      = f.select :unilateral, @boolean
    .form-group
      = f.label :notes
      = f.text_field :notes, placeholder: "Additional information (Optional)"
    .form-group
      = f.label :image
      = f.file_field :image, class: "form-control"
    = f.submit 'Save', class: 'btn'

app/views/exercises/index.html.haml
.title
  %h1= @workout.name
  = link_to start_workout_program_workout_path(@program, @workout), class: "btn btn-outline-success btn-sm" do
    %i.bi.bi-play.h4
  - if current_user.programs.include?(@program)
    = link_to copy_exercise_program_workout_path(@program, @workout), class: "btn btn-outline-primary btn-sm" do
      %i.bi.bi-plus.h4
.index
  %table
    %thead
      %tr
        %th Order
        %th Name
        %th Type
        %th Instrument
        %th Rep Range
        %th Rest Time
        %th Unilateral
        %th Notes
        %th Sets
        %th Actions
    %tbody
      - @exercises.each do |exercise|
        %tr
          %td= exercise.exercise_group.order
          %td= exercise.name
          %td= exercise.exercise_type
          %td= exercise.instrument.name
          %td= [exercise.rep_range_min, exercise.rep_range_max].join(" - ")
          %td= [exercise.rest_time, exercise.unit.abbreviation].join(" ")
          - if exercise.unilateral 
            %td
              %i.bi.bi-check
          - else
            %td
              %i.bi.bi-x
          %td= exercise.notes
          %td= exercise.exercise_sets.count
          %td.actions
            = link_to program_workout_exercise_path(@program, @workout, exercise), class: "btn" do
              %i.bi.bi-eye
            - if current_user.programs.include?(@program)
              = link_to edit_program_workout_exercise_path(@program, @workout, exercise), class: "btn" do
                %i.bi.bi-pencil
              = button_to duplicate_program_workout_exercise_path(@program, @workout, exercise), method: :post, data: { confirm: "Duplicate selected exercise?" }, class: "btn copy link" do
                %i.bi.bi-copy
              = button_to program_workout_exercise_path(@program, @workout, exercise), method: :delete, data: { confirm: "Are you sure?" }, class: "btn delete link" do
                %i.bi.bi-trash

app/views/exercises/quick_sets_creation.html.haml
.title
  %h1 Quick Set Creation
  = link_to new_program_workout_exercise_exercise_set_path(@program, @workout, @exercise), class: "btn btn-outline-primary btn-sm", title: "Create Custom Exercise Set" do
    %i.bi.bi-pencil.h5
.form
  = form_with model: [@program, @workout, @exercise], local: true do |f|
    .form-group
      = f.label :warmup_sets
      = f.number_field :warmup_sets, class: "form-control", value: 0
    .form-group
      = f.label :working_sets
      = f.number_field :working_sets, class: "form-control", value: 3
    .form-group
      = f.label :unit_id, "Additional Load Unit"
      = f.collection_select :unit_id, Unit.where(unit_type: "Weight"), :id, :name, { prompt: "Select Unit" }, class: "form-control"
    = f.submit "Save", class: "btn btn-primary"

app/views/exercises/show.html.haml
.title 
  %h1= @exercise.name
  - if current_user.programs.include?(@program)
    = link_to edit_program_workout_exercise_path(@program, @workout, @exercise), class:  "btn btn-outline-primary btn-sm" do
      %i.bi.bi-pencil.h5
    = link_to quick_sets_creation_program_workout_exercise_path(@program, @workout, @exercise), class:  "btn btn-outline-primary btn-sm" do
      %i.bi.bi-plus.h5
.show
  - if @exercise.image.attached?
    .flex-row
      = image_tag url_for(@exercise.image), class: "img-fluid"
  %table
    %tr
      %td.label Order
      %td.value= @exercise.exercise_group.order
    %tr
      %td.label Type
      %td.value= @exercise.exercise_type
    %tr
      %td.label Include Body Weight
      - if @exercise.body_weight 
        %td.value
          %i.bi.bi-check
      - else
        %td.value
          %i.bi.bi-x
    %tr
      %td.label Instrument
      %td.value= @exercise.instrument.name
    - if @exercise.attachment
      %tr
        %td.label Attachment
        %td.value= @exercise.attachment.name
    - if @exercise.hole
      %tr
        %td.label Hole Position
        %td.value= @exercise.hole
    - if @exercise.grip
      %tr
        %td.label Grip
        %td.value= @exercise.grip.name
    %tr
      %td.label Rep Range
      %td.value= [@exercise.rep_range_min, @exercise.rep_range_max].join(" - ")
    %tr
      %td.label Rest Time
      %td.value= [@exercise.rest_time, @exercise.unit.abbreviation].join(" ")
    %tr
      %td.label Unilateral
      - if @exercise.unilateral 
        %td.value
          %i.bi.bi-check
      - else
        %td.value
          %i.bi.bi-x
    - if @exercise.notes.present?
      %tr
        %td.label Notes
        %td.value= @exercise.notes
  - if @exercise.exercise_sets.any?
    = link_to 'Sets', program_workout_exercise_exercise_sets_path(@program, @workout, @exercise), class: "btn"

app/views/exercises/templates.html.haml
.scroll-container
  .scroll-row
    - @select_options.each do |mg|
      = link_to mg.name, exercise_templates_path(muscle_group: mg.id), class: mg == @muscle_group ? "btn btn-outline-primary btn-md me-2" : "btn btn-primary btn-md me-2"
.scroll-container
  .scroll-row
    - @muscle_group.muscles.each do |m|
      = link_to m.name, exercise_templates_path(muscle_group: @muscle_group.id, muscle: m.id), class: m == @muscle ? "btn btn-outline-secondary btn-md me-2" : "btn btn-secondary btn-md me-2"

.separator
//.title
//  %h1
//    = "Exercises for " + @muscle_group.name.capitalize
//    = " - " + @muscle.name if @muscle
//.separator
.flex-row.cards
  - @template_exercises.each do |exercise|
    - if exercise.image.attached?
      .card-wrapper
        = link_to program_workout_exercise_path(@program, @workout, exercise), class: "text-decoration-none" do
          .card.text-center
            .card-img-container
              = image_tag url_for(exercise.image), class: "card-img-top"
              .card-hover-overlay
                %div.card-hover-text
                  = exercise.muscles.map{ |m| m.name }.join(', ')
            .card-body
              %h4.card-title= exercise.name

:scss

  .scroll-container {
    width: 90vw;
    margin: auto;
    margin-top: 20px;
  }

  .scroll-row {
    display: flex;
    justify-content: center; // default for large screens
    overflow-x: auto;
    white-space: nowrap;
    gap: 10px;
    padding: 10px 20px;

    scroll-snap-type: x mandatory;
    scrollbar-width: thin;
    scrollbar-color: #888 transparent;

    &::-webkit-scrollbar {
      height: 8px;
    }

    &::-webkit-scrollbar-thumb {
      background: #888;
      border-radius: 4px;
    }

    &::-webkit-scrollbar-track {
      background: transparent;
    }

    @media (max-width: 1199.98px) {
      justify-content: flex-start;
    }
  }



  .flex-row.cards {
    display: flex;
    flex-wrap: wrap;
    gap: 40px; // adjust as needed
    justify-content: center; // optional for center alignment
  }

  .card-wrapper {
    position: relative;
    .card {
      width: 300px;
      height: 300px;
      overflow: hidden;
      transition: transform 0.2s ease-in-out;
      border: 1px solid #eeeeee; // customize thickness and color
      border-radius: 8px;
    }

    .card-body {
      display: flex;
      align-items: center;      // vertical center
      justify-content: center;  // horizontal center (optional)
      height: 100px;            // or flex-grow if you want it dynamic
      padding: 0 10px;
      text-align: center;
    }

    .card:hover {
      transform: scale(1.02);
    }

    .card-img-container {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 200px;
      padding: 10px;
    }

    .card-img-top {
      max-height: 100%;
      object-fit: contain;
    }

    .card-hover-overlay {
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      background-color: rgba(0, 0, 0, 0.5); // dark mask
      color: white;
      display: flex;
      align-items: center;
      justify-content: center;
      opacity: 0;
      transition: opacity 0.3s ease-in-out;
      text-align: center;
      padding: 10px;
    }

    .card-img-container:hover .card-hover-overlay {
      opacity: 1;
    }

    .card-hover-text {
      font-size: 1rem;
      font-weight: bold;
    }
  }