config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "/exercise_templates", to: "exercises#templates", as: :exercise_templates
  
  root "programs#quick_start"
  resources :users
  resources :programs do
    get :quick_start
    resources :workouts do
      member do
        get :copy_exercise
        get :start_workout
        get :preview_workout
      end
      resources :exercises do
        member do
          post :duplicate
          get :quick_sets_creation
        end
        resources :exercise_sets do
          member do
            post :duplicate
            get  :set_play_form
            get  :play_set
          end
        end
      end
    end
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %link{ rel: "icon", type: "image/x-icon", href: asset_path("favicon.ico") }
    %title Gymify
    %meta{name: "viewport", content: "width=device-width,initial-scale=1"}
    = csrf_meta_tags
    = csp_meta_tag
    %link{rel: "stylesheet", href: "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css"}
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body{ data: { turbo: "false" } }
    - if current_user
      %nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
        .container-fluid
          = link_to "Gymify 💪", root_path, class: "navbar-brand mb-0 h1"

          %button.navbar-toggler{ type: "button", "data-bs-toggle" => "collapse", "data-bs-target" => "#navbarNav" }
            %span.navbar-toggler-icon

          #navbarNav.collapse.navbar-collapse
            %ul.navbar-nav.me-auto
              %li.nav-item
                = link_to "Exercises", exercise_templates_path(), class: "nav-link"
              - if @program&.persisted?
                %li.nav-item
                  = link_to "Program", program_path(@program), class: "nav-link"
              - if @workout&.persisted?
                %li.nav-item
                  = link_to "Workout", program_workout_path(@program, @workout), class: "nav-link"
              - if @exercise&.persisted?
                %li.nav-item
                  = link_to "Exercise", program_workout_exercise_path(@program, @workout, @exercise), class: "nav-link"
              - if ["play_set", "start_workout", "set_play_form"].include?(controller.action_name) 
                %li.nav-item
                  = link_to "Preview", preview_workout_program_workout_path(@program, @workout), class: "nav-link", target: "_blank"

            %ul.navbar-nav.ms-auto
              %li.nav-item
                = link_to "My Programs", programs_path, class: "nav-link"
              %li.nav-item
                = link_to "Profile", user_path(current_user), class: "nav-link"
              %li.nav-item
                = button_to "Logout", destroy_user_session_path, method: :delete, data: { no_turbolink: true }, class: "nav-link"


    - if notice
      .alert.alert-success.alert-dismissible.fade.show{ role: "alert" }
        = notice
        %button.btn-close{"data-bs-dismiss" => "alert", "aria-label" => "Close"}

    - if alert
      .alert.alert-danger.alert-dismissible.fade.show{ role: "alert" }
        = alert
        %button.btn-close{"data-bs-dismiss" => "alert", "aria-label" => "Close"}

    .toast-container.position-fixed.top-20.start-50.translate-middle-x.p-3.z-3{id: "toast-container"}

    = yield